name = "xauz-music"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "xauz-music-db"
database_id = "d3419cb6-b901-4b87-9980-287b02ba1b87"
[vars]
ADMIN_PIN = "4246"